# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_queue.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'message_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13message_queue.proto\x12\tgenerated\":\n\x0ePublishRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\x12\x14\n\x0cmessage_body\x18\x02 \x01(\t\"3\n\x0fPublishResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x0e\x43onsumeRequest\x12\x12\n\nqueue_name\x18\x01 \x01(\t\";\n\x0f\x43onsumeResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x14\n\x0cmessage_body\x18\x02 \x01(\t2\xa0\x01\n\x0cMessageQueue\x12G\n\x0ePublishMessage\x12\x19.generated.PublishRequest\x1a\x1a.generated.PublishResponse\x12G\n\x0e\x43onsumeMessage\x12\x19.generated.ConsumeRequest\x1a\x1a.generated.ConsumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST']._serialized_start=34
  _globals['_PUBLISHREQUEST']._serialized_end=92
  _globals['_PUBLISHRESPONSE']._serialized_start=94
  _globals['_PUBLISHRESPONSE']._serialized_end=145
  _globals['_CONSUMEREQUEST']._serialized_start=147
  _globals['_CONSUMEREQUEST']._serialized_end=183
  _globals['_CONSUMERESPONSE']._serialized_start=185
  _globals['_CONSUMERESPONSE']._serialized_end=244
  _globals['_MESSAGEQUEUE']._serialized_start=247
  _globals['_MESSAGEQUEUE']._serialized_end=407
# @@protoc_insertion_point(module_scope)
